title: Receipt Analyzer

theme: minima
layout: default

include:
  - readme.md
  - azure_form_analyzer.md
  - api_details.md
  - technical_implementation.md

header_pages:
  - azure_form_analyzer.md
  - api_details.md
  - technical_implementation.md
